Import hooks/image/61-kolibri-content-download
This downloads Kolibri content from lists of channel and node ids. These
lists are hard-coded at the moment but will be split out into separate
configuration files.

https://phabricator.endlessm.com/T33670

diff --git a/stages/ekb_content b/stages/ekb_content
--- a/stages/ekb_content
+++ b/stages/ekb_content
@@ -102,3 +102,56 @@ pip install ${PYPI_ZIM_PLUGIN_VERSION} --target="${KOLIBRI_HOME}/extensions" --p
 # Install apps bundle
 ekb_download_file "${apps_url}" "${EKB_TMP_DIR}/apps-bundle.zip"
 unzip -o -d "${KOLIBRI_HOME}/extensions/kolibri_explore_plugin" "${EKB_TMP_DIR}/apps-bundle.zip"
+
+
+## hooks/image/61-kolibri-content-download
+
+# Populate the Kolibri home directory
+
+# Use a separate content URL if configured.
+if [ -n "${EKB_KOLIBRI_CENTRAL_CONTENT_BASE_URL}" ]; then
+  KOLIBRI_CENTRAL_CONTENT_BASE_URL="${EKB_KOLIBRI_CENTRAL_CONTENT_BASE_URL}"
+  export KOLIBRI_CENTRAL_CONTENT_BASE_URL
+fi
+
+import_kolibri_channel()
+{
+  local channel_id=$1
+  local channel_include_node_ids_var="EKB_KOLIBRI_${channel_id^^}_INCLUDE_NODE_IDS"
+  local channel_exclude_node_ids_var="EKB_KOLIBRI_${channel_id^^}_EXCLUDE_NODE_IDS"
+  local importcontent_opts=(
+    # Normally importcontent ignores download errors. Make it fail so we
+    # can be sure we've fully provisioned channels.
+    --fail-on-error
+  )
+  local importcontent_network_opts=(
+    # The default timeout is 60 seconds, but downloading can be slow
+    # when objects aren't in our content CDN yet.
+    --timeout 300
+  )
+
+  if [ -n "${!channel_include_node_ids_var}" ]; then
+    importcontent_include_nodes=$(echo "${!channel_include_node_ids_var}" | xargs | tr -s ' ' ',')
+    importcontent_opts+=(--node_ids="${importcontent_include_nodes}")
+  fi
+
+  if [ -n "${!channel_exclude_node_ids_var}" ]; then
+    importcontent_exclude_nodes=$(echo "${!channel_exclude_node_ids_var}" | xargs | tr -s ' ' ',')
+    importcontent_opts+=(--exclude_node_ids="${importcontent_exclude_nodes}")
+  fi
+
+  kolibri manage importchannel network "${channel_id}"
+  kolibri manage importcontent "${importcontent_opts[@]}" \
+    network "${importcontent_network_opts[@]}" "${channel_id}"
+}
+
+for channel_id in ${EKB_KOLIBRI_INSTALL_CHANNELS}; do
+  import_kolibri_channel "${channel_id}"
+done
+
+# Sort channels in the same order as in EKB_KOLIBRI_INSTALL_CHANNELS
+position=1
+for channel_id in ${EKB_KOLIBRI_INSTALL_CHANNELS}; do
+  kolibri manage setchannelposition ${channel_id} ${position} || true
+  let position=position+1
+done
